#!/bin/bash -e

# debirf module: n0_base
# base network configuration

# reset default udev persistent-net rule
rm -f "${DEBIRF_ROOT}"/etc/udev/rules.d/*_persistent-net.rules

# /etc/resolv.conf symlink
rm -f "${DEBIRF_ROOT}"/etc/resolv.conf
debirf_exec ln -s "/run/systemd/resolve/resolv.conf" "/etc/resolv.conf"

debirf_exec systemctl reenable systemd-networkd
debirf_exec systemctl reenable systemd-resolved
debirf_exec systemctl reenable systemd-timesyncd
debirf_exec systemctl reenable systemd-networkd-wait-online.service
