#!/bin/bash -e

debirf_exec apt-get --no-install-recommends --assume-yes install firmware-brcm80211 wpasupplicant crda

IFNAME=`basename $0 | cut -d _ -f 2`

cat <<EOF > "${DEBIRF_ROOT}/etc/systemd/network/${IFNAME}.network"
[Match]
name=${IFNAME}
[Network]
DHCP=yes
EOF

cat <<EOF > "${DEBIRF_ROOT}/etc/systemd/system/wpa_supplicant@.service"
[Unit]
Description=WPA supplicant daemon (interface-specific version)
Requires=sys-subsystem-net-devices-%i.device
After=sys-subsystem-net-devices-%i.device
Before=network.target
Wants=network.target

[Service]
Type=simple
ExecStart=/sbin/wpa_supplicant -c/etc/wpa_supplicant/wpa_supplicant-%I.conf -Dnl80211,wext -i%I

[Install]
Alias=multi-user.target.wants/wpa_supplicant@%i.service
EOF

debirf_exec systemctl reenable wpa_supplicant@${IFNAME}.service
