#!/bin/bash -e

debirf_exec apt-get --no-install-recommends --assume-yes install firmware-brcm80211 wpasupplicant crda

IFNAME=`basename $0 | cut -d _ -f 2`

cat <<EOF > "${DEBIRF_ROOT}/etc/network/interfaces.d/${IFNAME}"
allow-hotplug ${IFNAME}
iface ${IFNAME} inet manual
    wpa-conf /etc/wpa_supplicant/wpa_supplicant.conf
EOF
