#!/bin/bash -e

# This doesn't really work properly. pupnp does not handle interface changes
# so attempt to make dhcpcd wait until one interface is configured.
# Hope it is the one you actually want to use.

# I highly recommend using rygel instead.

debirf_exec apt-get --assume-yes --no-install-recommends install gmediarender gstreamer1.0-plugins-good gstreamer1.0-plugins-ugly gstreamer1.0-alsa alsa-utils

rm -f "${DEBIRF_ROOT}/etc/init.d/gmediarender"

cat <<EOF > "${DEBIRF_ROOT}/etc/systemd/system/gmediarender.service"
[Unit]
Description=uPNP Media Renderer
After=network-online.target sound.target

[Service]
ExecStart=/usr/bin/gmediarender
Restart=on-abort

[Install]
WantedBy=multi-user.target
EOF


# we need for at least one interface to have a real IP
# so tell dhcpcd to wait.

mkdir "${DEBIRF_ROOT}/etc/systemd/system/dhcpcd.service.d"

cat <<EOF > "${DEBIRF_ROOT}/etc/systemd/system/gmediarender.service"
[Service]
ExecStart=
ExecStart=/sbin/dhcpcd -q -w
EOF


debirf_exec systemctl reenable gmediarender
debirf_exec systemctl reenable dhcpcd
