#!/bin/bash -e

if [ ! -d /opt/gstreamer-1.0 ]; then
    echo "Gstreamer installation not found."
    exit 255
fi

debirf_exec apt-get --no-install-recommends --assume-yes install libasound2 libglib2.0-0 libjpeg62-turbo libreadline5 zlib1g libflac8 libmpg123-0 libvorbis0a

mkdir -p "$DEBIRF_ROOT/opt"

cp -a /opt/gstreamer-1.0 "$DEBIRF_ROOT/opt/"

cd "$DEBIRF_ROOT"
rm -rf opt/gstreamer-1.0/include
rm -rf opt/gstreamer-1.0/share
rm -rf opt/gstreamer-1.0/bin/orc*

cp /etc/ld.so.conf.d/gstreamer-1.0.conf "$DEBIRF_ROOT/etc/ld.so.conf.d/"
