#!/bin/bash -e

# Install Rygel built from source.

if [ ! -d /opt/rygel ]; then
    echo "Rygel installation not found."
    exit 255
fi

debirf_exec apt-get --no-install-recommends --assume-yes install libgee-0.8-2 libxml2 libsoup2.4-1

mkdir -p "$DEBIRF_ROOT/opt"

cp -a /opt/rygel "$DEBIRF_ROOT/opt/"

cd "$DEBIRF_ROOT"
rm -rf opt/rygel/share/locale
rm -rf opt/rygel/share/gir-1.0
rm -rf opt/rygel/share/vala
rm -rf opt/rygel/include

cp /etc/ld.so.conf.d/rygel.conf "$DEBIRF_ROOT/etc/ld.so.conf.d/"
