#!/bin/bash -e

cat <<EOF > "${DEBIRF_ROOT}/root/update"
#!/bin/sh -e

mount /boot/ || echo Already mounted...
cd /boot/
rm -f firmware.tar.gz
wget \$1/firmware.tar.gz
tar --no-same-owner -xf firmware.tar.gz
cd /
umount /boot/
sync
sync
sync
EOF

chmod a+x "${DEBIRF_ROOT}/root/update"
